Add a bunch of sh-mode snippets

diff --git a/snippets/sh-mode/header b/snippets/sh-mode/header
--- a/snippets/sh-mode/header
+++ b/snippets/sh-mode/header
@@ -2,9 +2,15 @@
 # name: header
 # key: header
 # --
-#!/bin/${1:sh}
+#!/bin/${1:ba}sh
 # Author: ${2:Guillermo Robles}
 #
 # ${3:description}
 
+${4:set -e                          # Exit if pipeline returns non zero
+}${5:set -u                          # Errors on unset variables usage
+}${6:set -o pipefail                 # The return value of pipeline is the return value of the rightmost command to exit with a non-zero, or zero if all commands exit succesfully
+}${7:
+IFS=$'\n\t'                     # Modifies the IFS
+}
 $0
